#!/bin/sh
VIP=${VIP?"mandatory parameter: <ip>/<prefix>"}
VNI=${VNI:='10'}
VXLAN=${VXLAN:="vxlan$VNI"}
IF=${IF:="eth0"}
HOSTS=${HOSTS:=""}

eval `ipcalc -b $VIP`
install(){
  ip link add $VXLAN type vxlan id $VNI dev $IF 2>/dev/null
  ip link set $VXLAN up
  ip a add $VIP broadcast $BROADCAST dev $VXLAN
  for H in $HOSTS; do
    bridge fdb append 00:00:00:00:00:00 dev $VXLAN dst $H
  done
  echo "$VXLAN installed ($VIP) on $IF"
}
uninstall(){
  ip li delete $VXLAN type vxlan
  echo "$VXLAN uninstalled ($VIP) from $IF"
}
install
trap 'uninstall' EXIT
trap 'exit 0' SIGTERM
tail -f /dev/null &
wait
