#!/bin/sh
VIPS=`echo ${VIP?"mandatory parameter: <ip>/<prefix>[,...]"} | tr "," "\n"`
VNI=${VNI:='10'}
VXLAN=${VXLAN:="vxlan$VNI"}
IF=${IF:="eth0"}
PORT=${PORT:="0"}
MTU=${MTU:="1410"}
HOSTS=`echo ${HOSTS:=""} | tr "," "\n"`

check(){
  until $1 2>1 >/dev/null; do usleep 100000; done
}
vxlan_found(){
  ip a show $VXLAN 2>&1 >/dev/null
}
addr_found(){
  ip a show $VXLAN to $1 | grep . 2>&1 >/dev/null
}

until vxlan_found; do
  ip link add $VXLAN mtu $MTU type vxlan id $VNI dev $IF dstport $PORT
done
echo "$VXLAN installed on $IF"
for I in $VIPS; do
  eval `ipcalc -hb $I` # HOSTNAME and BROADCAST
  check "ip link set $VXLAN up"
  until addr_found $HOSTNAME; do
    check "ip a add $I broadcast $BROADCAST dev $VXLAN"
  done
  echo "$I added to $VXLAN"
done
for H in $HOSTS; do
  check "bridge fdb append 00:00:00:00:00:00 dev $VXLAN dst $H"
done
trap 'exit 0' SIGTERM
tail -f /dev/null &
wait
